### ISSUE TITLE
RuntimeError: Execution stopped:

### ISSUE THREAD

**Issue by CrazyCoder4Carrot** [snap-stanford/ringo#1]
I have installed python and Ringo on my computer. When I run the demo usecae.py you provided in the tutorial. I got an error:
Traceback (most recent call last):
  File "usecase.py", line 12, in <module>
    QA = ringo.Join(Q, A, 'AcceptedAnswerId', 'Id')
  File "/home/lzb/Dropbox/GWU/Lab/VisualGraph/Reference/Ringo/mydemo/ringo.py", line 37, in wrapper
    RetVal = func(_unpack_args, *_kwargs)
  File "/home/lzb/Dropbox/GWU/Lab/VisualGraph/Reference/Ringo/mydemo/ringo.py", line 583, in Join
    JoinT = LeftT.Join(LeftAttr, RightT, RightAttr)
RuntimeError: Execution stopped: (0<=ValN)&&(ValN<Vals) [Reason:'Index:-2 Vals:99999 MxVals:99999 Type:4TVecI4TIntiE'], file ../../snap/glib-core/ds.h, line 455
terminate called after throwing an instance of 'TPt<TExcept>'
Aborted (core dumped)

I have tried it on ubuntu and centOS. Both of them are 64bit version OS.

**Comment by roks** [comment]
Thanks for the report. We were able to reproduce the problem. We are currently in the process of a major code reorganization and will investigate this issue in detail once the reorganization is completed.

**Comment by TPNguyen** [comment]
I got this error when running the usecase.py (2nd line). I got this error on both of Windows and Ubuntu OS;.

Schema = [('Id','int'), ('PostTypeId','int'), ('AcceptedAnswerId','int'), ('OwnerUserId','int'), ('Body','string'), ('Tag','string')]

ringo = ringo.Ringo()
Traceback (most recent call last):

  File "<ipython-input-10-0e25e16ce456>", line 1, in <module>
    ringo = ringo.Ringo()

  File "C:\Anaconda\lib\site-packages\ringo.py", line 117, in **init**
    self.Context = snap.TTableContext()

AttributeError: 'module' object has no attribute 'TTableContext'

**Comment by dalton** [comment]
I'm running into the same issue trying to work through the [example](http://snap.stanford.edu/ringo/#example). Is there any updated documentation?

**Comment by dalton** [comment]
I tried walking throught the 12-usecase.py in /test-ringo and got a different error. Not sure if this is useful. Is it possible that my installation of SNAP is out of sync with Ringo 0.1?

```
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ringo
>>> import snap
>>> import sys
>>> import os
>>> srcfile="posts.tsv"
>>> ringo = ringo.Ringo()
>>> Schema = [('Id','int'), ('PostTypeId','int'), ('AcceptedAnswerId','int'),
...           ('OwnerUserId','int'), ('Body','string'), ('Tag','string')]
>>> S = Schema
>>> P = ringo.LoadTableTSV(Schema, 'posts.tsv', '\t', True)
>>> table = P
>>> questions = ringo.Select(table, "Tag = 'java'", False)
>>> qa = ringo.Join(questions, table, "AcceptedAnswerId", "Id")
*** Error in `python': double free or corruption (!prev): 0x00007f5fa4000b60 ***
*** Error in `python': double free or corruption (!prev): 0x00007f5fa4000b60 ***
*** Error in `python': double free or corruption (!prev): 0x00007f5fa4000b60 ***
======= Backtrace: =========
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f5fe2cae503]
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f5fe2cae503]
/usr/lib64/python2.7/site-packages/_snap.so(_ZN4TVecI4TIntiE6ResizeERKi+0xdd)[0x7f5fd9c9c45d]
/lib64/libc.so.6(+0x7c503)[0x7f5fe2cae503]
/usr/lib64/python2.7/site-packages/_snap.so(_ZN4TVecI4TIntiE6ResizeERKi+0xdd)[0x7f5fd9c9c45d]
/usr/lib64/python2.7/site-packages/_snap.so(_ZN4TVecI4TIntiE3AddERS0_+0x6d)[0x7f5fda326b3d]
/usr/lib64/python2.7/site-packages/_snap.so(_ZNK6TTable14UpdateGroupingI4TIntEEvR7THashMPIT_4TVecIS1_iE16TDefaultHashFuncIS3_EES3_S1_+0xae)[0x7f5fda34e2ce]
/usr/lib64/python2.7/site-packages/_snap.so(_ZN4TVecI4TIntiE3AddERS0_+0x6d)[0x7f5fda326b3d]
/usr/lib64/python2.7/site-packages/_snap.so(_ZNK6TTable14UpdateGroupingI4TIntEEvR7THashMPIT_4TVecIS1_iE16TDefaultHashFuncIS3_EES3_S1_+0xae)[0x7f5fda34e2ce]
/usr/lib64/python2.7/site-packages/_snap.so(+0x160eefd)[0x7f5fda162efd]
/lib64/libgomp.so.1(+0x16435)[0x7f5fd8433435]
/lib64/libpthread.so.0(+0x7dc5)[0x7f5fe3703dc5]
/lib64/libc.so.6(clone+0x6d)[0x7f5fe2d2973d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:04 2761928                            /usr/bin/python2.7
00600000-00601000 r--p 00000000 08:04 2761928                            /usr/bin/python2.7
00601000-00602000 rw-p 00001000 08:04 2761928                            /usr/bin/python2.7
0201c000-0350a000 rw-p 00000000 00:00 0                                  [heap]
7f5f7c000000-7f5f7c021000 rw-p 00000000 00:00 0 
7f5f7c021000-7f5f80000000 ---p 00000000 00:00 0 
7f5f84000000-7f5f84021000 rw-p 00000000 00:00 0 
7f5f84021000-7f5f88000000 ---p 00000000 00:00 0 
7f5f88000000-7f5f88021000 rw-p 00000000 00:00 0 
7f5f88021000-7f5f8c000000 ---p 00000000 00:00 0 
7f5f8c000000-7f5f8c021000 rw-p 00000000 00:00 0 
7f5f8c021000-7f5f90000000 ---p 00000000 00:00 0 
7f5f94000000-7f5f94021000 rw-p 00000000 00:00 0 
7f5f94021000-7f5f98000000 ---p 00000000 00:00 0 
7f5f9c000000-7f5f9c021000 rw-p 00000000 00:00 0 
7f5f9c021000-7f5fa0000000 ---p 00000000 00:00 0 
7f5fa0000000-7f5fa0021000 rw-p 00000000 00:00 0 
7f5fa0021000-7f5fa4000000 ---p 00000000 00:00 0 
7f5fa4000000-7f5fa4021000 rw-p 00000000 00:00 0 
7f5fa4021000-7f5fa8000000 ---p 00000000 00:00 0 
7f5fa8000000-7f5fa8021000 rw-p 00000000 00:00 0 
7f5fa8021000-7f5fac000000 ---p 00000000 00:00 0 
7f5fac000000-7f5fac021000 rw-p 00000000 00:00 0 
7f5fac021000-7f5fb0000000 ---p 00000000 00:00 0 
7f5fb0000000-7f5fb0021000 rw-p 00000000 00:00 0 
7f5fb0021000-7f5fb4000000 ---p 00000000 00:00 0 
7f5fb4000000-7f5fb4021000 rw-p 00000000 00:00 0 
7f5fb4021000-7f5fb8000000 ---p 00000000 00:00 0 
7f5fb8000000-7f5fb8021000 rw-p 00000000 00:00 0 
7f5fb8021000-7f5fbc000000 ---p 00000000 00:00 0 
7f5fbc000000-7f5fbc021000 rw-p 00000000 00:00 0 
7f5fbc021000-7f5fc0000000 ---p 00000000 00:00 0 
7f5fc0000000-7f5fc0021000 rw-p 00000000 00:00 0 
7f5fc0021000-7f5fc4000000 ---p 00000000 00:00 0 
7f5fc4000000-7f5fc4021000 rw-p 00000000 00:00 0 
7f5fc4021000-7f5fc8000000 ---p 00000000 00:00 0 
7f5fca85f000-7f5fca860000 ---p 00000000 00:00 0 
7f5fca860000-7f5fcb060000 rw-p 00000000 00:00 0                          [stack:25096]
7f5fcb060000-7f5fcb061000 ---p 00000000 00:00 0 
7f5fcb061000-7f5fcb861000 rw-p 00000000 00:00 0                          [stack:25095]
7f5fcb861000-7f5fcb862000 ---p 00000000 00:00 0 
7f5fcb862000-7f5fcc062000 rw-p 00000000 00:00 0                          [stack:25094]
7f5fcc062000-7f5fcc063000 ---p 00000000 00:00 0 
7f5fcc063000-7f5fcc863000 rw-p 00000000 00:00 0                          [stack:25093]
7f5fcc863000-7f5fcc864000 ---p 00000000 00:00 0 
7f5fcc864000-7f5fcd064000 rw-p 00000000 00:00 0                          [stack:25092]
7f5fcd064000-7f5fcd065000 ---p 00000000 00:00 0 
7f5fcd065000-7f5fcd865000 rw-p 00000000 00:00 0                          [stack:25091]
7f5fcd865000-7f5fcd866000 ---p 00000000 00:00 0 
7f5fcd866000-7f5fce066000 rw-p 00000000 00:00 0                          [stack:25090]
7f5fce066000-7f5fce067000 ---p 00000000 00:00 0 
7f5fce067000-7f5fce867000 rw-p 00000000 00:00 0                          [stack:25089]
7f5fce867000-7f5fce868000 ---p 00000000 00:00 0 
7f5fce868000-7f5fcf068000 rw-p 00000000 00:00 0                          [stack:25088]
7f5fcf068000-7f5fcf069000 ---p 00000000 00:00 0 
7f5fcf069000-7f5fcf869000 rw-p 00000000 00:00 0                          [stack:25087]
7f5fcf869000-7f5fcf86a000 ---p 00000000 00:00 0 
7f5fcf86a000-7f5fd006a000 rw-p 00000000 00:00 0                          [stack:25086]
7f5fd006a000-7f5fd006b000 ---p 00000000 00:00 0 
7f5fd006b000-7f5fd086b000 rw-p 00000000 00:00 0                          [stack:25085]
7f5fd086b000-7f5fd286c000 rw-p 00000000 00:00 0 
7f5fd296a000-7f5fd296b000 ---p 00000000 00:00 0 
7f5fd296b000-7f5fd316b000 rw-p 00000000 00:00 0                          [stack:25084]
7f5fd316b000-7f5fd316c000 ---p 00000000 00:00 0 
7f5fd316c000-7f5fd396c000 rw-p 00000000 00:00 0                          [stack:25083]
7f5fd396c000-7f5fd396d000 ---p 00000000 00:00 0 
7f5fd396d000-7f5fd456f000 rw-p 00000000 00:00 0                          [stack:25082]
7f5fd4670000-7f5fd4771000 rw-p 00000000 00:00 0 
7f5fd4771000-7f5fd4776000 r-xp 00000000 08:04 2760983                    /usr/lib64/python2.7/lib-dynload/binascii.so
7f5fd4776000-7f5fd4975000 ---p 00005000 08:04 2760983                    /usr/lib64/python2.7/lib-dynload/binascii.so
7f5fd4975000-7f5fd4976000 r--p 00004000 08:04 2760983                    /usr/lib64/python2.7/lib-dynload/binascii.so
7f5fd4976000-7f5fd4977000 rw-p 00005000 08:04 2760983                    /usr/lib64/python2.7/lib-dynload/binascii.so
7f5fd4977000-7f5fd497f000 r-xp 00000000 08:04 2778817                    /usr/lib64/python2.7/lib-dynload/_json.so
7f5fd497f000-7f5fd4b7e000 ---p 00008000 08:04 2778817                    /usr/lib64/python2.7/lib-dynload/_json.so
7f5fd4b7e000-7f5fd4b7f000 r--p 00007000 08:04 2778817                    /usr/lib64/python2.7/lib-dynload/_json.so
7f5fd4b7f000-7f5fd4b80000 rw-p 00008000 08:04 2778817                    /usr/lib64/python2.7/lib-dynload/_json.so
7f5fd4b80000-7f5fd4b87000 r-xp 00000000 08:04 2778822                    /usr/lib64/python2.7/lib-dynload/_struct.so
7f5fd4b87000-7f5fd4d86000 ---p 00007000 08:04 2778822                    /usr/lib64/python2.7/lib-dynload/_struct.so
7f5fd4d86000-7f5fd4d87000 r--p 00006000 08:04 2778822                    /usr/lib64/python2.7/lib-dynload/_struct.so
7f5fd4d87000-7f5fd4d89000 rw-p 00007000 08:04 2778822                    /usr/lib64/python2.7/lib-dynload/_struct.so
7f5fd4d89000-7f5fd4d8d000 r-xp 00000000 08:04 2778827                    /usr/lib64/python2.7/lib-dynload/cStringIO.soAborted (core dumped)
```
